#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace my_setup
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="trucksModification")]
	public partial class dabaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Définitions de méthodes d'extensibilité
    partial void OnCreated();
    partial void InsertChauffeur(Chauffeur instance);
    partial void UpdateChauffeur(Chauffeur instance);
    partial void DeleteChauffeur(Chauffeur instance);
    #endregion
		
		public dabaDataContext() : 
				base(global::my_setup.Properties.Settings.Default.trucksModificationConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dabaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dabaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dabaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dabaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Chauffeur> Chauffeur
		{
			get
			{
				return this.GetTable<Chauffeur>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.nbChauffeur")]
		public ISingleResult<nbChauffeurResult> nbChauffeur()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<nbChauffeurResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Chauffeur")]
	public partial class Chauffeur : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _cinChauffeur;
		
		private string _idContrat;
		
		private string _nomChauffeur;
		
		private string _prenomChauffeur;
		
		private string _typePermis;
		
		private System.Nullable<decimal> _salaireChauffeur;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncinChauffeurChanging(string value);
    partial void OncinChauffeurChanged();
    partial void OnidContratChanging(string value);
    partial void OnidContratChanged();
    partial void OnnomChauffeurChanging(string value);
    partial void OnnomChauffeurChanged();
    partial void OnprenomChauffeurChanging(string value);
    partial void OnprenomChauffeurChanged();
    partial void OntypePermisChanging(string value);
    partial void OntypePermisChanged();
    partial void OnsalaireChauffeurChanging(System.Nullable<decimal> value);
    partial void OnsalaireChauffeurChanged();
    #endregion
		
		public Chauffeur()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cinChauffeur", DbType="VarChar(255) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string cinChauffeur
		{
			get
			{
				return this._cinChauffeur;
			}
			set
			{
				if ((this._cinChauffeur != value))
				{
					this.OncinChauffeurChanging(value);
					this.SendPropertyChanging();
					this._cinChauffeur = value;
					this.SendPropertyChanged("cinChauffeur");
					this.OncinChauffeurChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idContrat", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string idContrat
		{
			get
			{
				return this._idContrat;
			}
			set
			{
				if ((this._idContrat != value))
				{
					this.OnidContratChanging(value);
					this.SendPropertyChanging();
					this._idContrat = value;
					this.SendPropertyChanged("idContrat");
					this.OnidContratChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomChauffeur", DbType="VarChar(255)")]
		public string nomChauffeur
		{
			get
			{
				return this._nomChauffeur;
			}
			set
			{
				if ((this._nomChauffeur != value))
				{
					this.OnnomChauffeurChanging(value);
					this.SendPropertyChanging();
					this._nomChauffeur = value;
					this.SendPropertyChanged("nomChauffeur");
					this.OnnomChauffeurChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prenomChauffeur", DbType="VarChar(255)")]
		public string prenomChauffeur
		{
			get
			{
				return this._prenomChauffeur;
			}
			set
			{
				if ((this._prenomChauffeur != value))
				{
					this.OnprenomChauffeurChanging(value);
					this.SendPropertyChanging();
					this._prenomChauffeur = value;
					this.SendPropertyChanged("prenomChauffeur");
					this.OnprenomChauffeurChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_typePermis", DbType="VarChar(255)")]
		public string typePermis
		{
			get
			{
				return this._typePermis;
			}
			set
			{
				if ((this._typePermis != value))
				{
					this.OntypePermisChanging(value);
					this.SendPropertyChanging();
					this._typePermis = value;
					this.SendPropertyChanged("typePermis");
					this.OntypePermisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salaireChauffeur", DbType="Money")]
		public System.Nullable<decimal> salaireChauffeur
		{
			get
			{
				return this._salaireChauffeur;
			}
			set
			{
				if ((this._salaireChauffeur != value))
				{
					this.OnsalaireChauffeurChanging(value);
					this.SendPropertyChanging();
					this._salaireChauffeur = value;
					this.SendPropertyChanged("salaireChauffeur");
					this.OnsalaireChauffeurChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class nbChauffeurResult
	{
		
		private System.Nullable<int> _nb;
		
		public nbChauffeurResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nb", DbType="Int")]
		public System.Nullable<int> nb
		{
			get
			{
				return this._nb;
			}
			set
			{
				if ((this._nb != value))
				{
					this._nb = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
